M48
; DRILL file {KiCad 7.0.5} date Wed Oct 11 12:04:12 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-11T12:04:12-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X5.3543Y-3.3661
X5.3543Y-3.7205
X5.3543Y-4.0748
T0
M30
